Projekt
Agnieszka Urban
Nr indeksu: 116866

In [1]:
!pip install pandas
!pip install numpy
!pip install openpyxl

Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Requirement already satisfied: numpy in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.21.6)
Collecting openpyxl
  Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 KB 14.2 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10

In [2]:
import pandas as pd
import numpy as np

Wczytywanie danych przygotowanych w formie pliku w excelu

In [3]:
file = pd.read_excel("Dane.xlsx")
file

,Województwo,Ludność,Pracujący,Procent pracujących,Bezrobotni,Procent bezrobotnych,Liczba małżeństw na 1000 mieszkańców,Liczba ośrodków kultury,Powierzchnia gruntów leśnych w ha,Drogi ekspresowe i autostrady na 1 tys km2,Nakłady wewnętrzne na działalność B+R na 1 mieszkańca
0,Śląskie,4570849,1602288,0.350545,119981.0,0.026249,5.0,368,82716.41,24.84,263.9
1,Dolnośląskie,2904198,1073968,0.369798,85984.0,0.029607,4.8,337,28067.79,14.35,371.8
2,Mazowieckie,5349114,3083601,0.576469,188910.0,0.035316,5.0,287,373949.87,7.17,1284.0
3,Małopolskie,3372618,1341683,0.397816,96531.0,0.028622,5.3,449,202140.16,11.38,946.9
4,Wielkopolskie,3475323,1547439,0.445265,77697.0,0.022357,5.3,314,90346.22,12.09,310.9
5,Zachodniopomorskie,1710482,501784,0.293358,65842.0,0.038493,4.8,358,25414.71,7.01,110.4
6,Łódzkie,2493603,929675,0.372824,91041.0,0.036510,4.7,197,137281.40,24.66,281.1
7,Pomorskie,2307710,781006,0.338433,64132.0,0.027790,5.4,326,80700.38,7.55,535.5
8,Opolskie,996011,295057,0.296239,32419.0,0.032549,4.9,217,13991.00,9.36,138.7
9,Kujawsko-pomorskie,2086210,671195,0.321729,98522.0,0.047225,5.0,215,53017.54,11.13,139.1
10,Lubuskie,1018084,311269,0.305740,32367.0,0.031792,5.0,81,14759.45,16.89,82.4
11,Podkarpackie,2127657,778570,0.365928,107567.0,0.050557,5.2,372,149495.97,9.16,358.7
12,Świętokrzyskie,1257179,444148,0.353289,57126.0,0.045440,4.8,121,96701.06,4.88,106.9
13,Lubelskie,2139726,801825,0.374733,95596.0,0.044677,5.0,218,241918.53,3.55,292.6
14,Warmińsko-mazurskie,1439675,406458,0.282326,73079.0,0.050761,4.7,160,64626.06,6.06,115.0
15,Podlaskie,1188800,394445,0.331801,48361.0,0.040681,5.3,184,204878.07,3.03,149.5

Proces normowania kolumn

In [4]:
data = pd.read_excel("Dane.xlsx", usecols="G:K")
#otrzymanie wymiarów utworzonej tablicy
numbers = data.shape
#zczytanie liczby kolumn oraz liczby wierszy utworzonej tablicy
number_of_columns = numbers[1]
number_of_rows = numbers[0]
array = data.to_numpy()
#prelokacja tablic, tak aby uniknąć dynamicznego alokowania pamięci - uzupełnienie tablic zerami
maxelement = np.zeros(number_of_columns)
normalized_array = np.zeros((number_of_rows, number_of_columns))
#proces normowania kolumn
for i in range(number_of_columns):
  maxelement[i] = np.amax(array[0:number_of_rows, i])
  for j in range(number_of_rows):
    normalized_array[j, i] = array[j, i]/maxelement[i]
data_p2 = pd.read_excel("Dane.xlsx", usecols="D,F")
array_p2 = data_p2.to_numpy()

Ze względu na to, że bezrobotni są destymuantą ich wskaźnik musi być ujemny

In [5]:
for i in range(number_of_rows):
  array_p2[i, 1] = array_p2[i, 1]*(-1)

Tworzenie tablicy wskaźników cząstkowych unormowanych

In [6]:
rows = [['Śląskie'], ['Dolnośląskie'], ['Mazowieckie'], ['Małopolskie'], ['Wielkopolskie'], ['Zachodniopomorskie'], ['Łódzkie'], ['Pomorskie'],
        ['Opolskie'], ['Kujawsko-pomorskie'], ['Lubuskue'], ['Podkarpackie'], ['Świętokrzyskie'], ['Lubelskie'], ['Warmińsko-mazurskie'], ['Podlaskie']]
prepared_data = np.concatenate((normalized_array, array_p2), axis=1)
named_data = np.concatenate((rows, prepared_data), axis=1)
indicators = pd.DataFrame(named_data, columns=['Województwo', 'Wskaźnik małżeństw', 'Wskaźnik kultury',
                          'Wskaźnik gruntów leśnych', 'Wskaźnik dróg', 'Wskaźnik B+R', 'Wskaźnik pracujących', 'Wskaźnik bezrobotnych'])
indicators

,Województwo,Wskaźnik małżeństw,Wskaźnik kultury,Wskaźnik gruntów leśnych,Wskaźnik dróg,Wskaźnik B+R,Wskaźnik pracujących,Wskaźnik bezrobotnych
0,Śląskie,0.9259259259259258,0.8195991091314031,0.22119652027155406,1.0,0.2055295950155763,0.3505449425259946,-0.026249171652793606
1,Dolnośląskie,0.8888888888888888,0.7505567928730512,0.07505762737663206,0.5776972624798712,0.2895638629283489,0.3697984779274691,-0.029606796781762125
2,Mazowieckie,0.9259259259259258,0.6391982182628062,1.0,0.2886473429951691,1.0,0.5764694863485803,-0.03531612898883815
3,Małopolskie,0.9814814814814814,1.0,0.5405541657228013,0.45813204508856686,0.7374610591900311,0.3978164737304966,-0.028621978534183235
4,Wielkopolskie,0.9814814814814814,0.6993318485523385,0.2415998165743446,0.4867149758454106,0.24213395638629281,0.4452647998473811,-0.022356770867053222
5,Zachodniopomorskie,0.8888888888888888,0.7973273942093542,0.06796287962341048,0.2822061191626409,0.08598130841121496,0.2933582463890295,-0.03849324342495273
6,Łódzkie,0.8703703703703703,0.43875278396436523,0.3671117735647294,0.9927536231884058,0.21892523364485983,0.37282398200515476,-0.036509821330821306
7,Pomorskie,1.0,0.7260579064587973,0.21580534310655064,0.30394524959742353,0.41705607476635514,0.3384333386777368,-0.027790320274211234
8,Opolskie,0.9074074074074074,0.48329621380846327,0.03741410579979611,0.3768115942028985,0.10802180685358255,0.2962386961589782,-0.03254883731203771
9,Kujawsko-pomorskie,0.9259259259259258,0.47884187082405344,0.14177713178507056,0.4480676328502416,0.10833333333333332,0.32172935610509007,-0.047225351235014694
10,Lubuskue,0.9259259259259258,0.18040089086859687,0.03946906038501899,0.6799516908212561,0.06417445482866044,0.3057399978783676,-0.03179207216693318
11,Podkarpackie,0.9629629629629629,0.8285077951002228,0.3997754297922339,0.36876006441223835,0.2793613707165109,0.3659283427732948,-0.05055655117342692
12,Świętokrzyskie,0.8888888888888888,0.26948775055679286,0.25859364518565015,0.19645732689210949,0.08325545171339564,0.3532893883846294,-0.04543982996852477
13,Lubelskie,0.9259259259259258,0.48552338530066813,0.6469277018334035,0.142914653784219,0.22788161993769473,0.37473255921552573,-0.044676748331328404
14,Warmińsko-mazurskie,0.8703703703703703,0.35634743875278396,0.17282011623643564,0.2439613526570048,0.0895638629283489,0.28232621945925296,-0.05076076197752965
15,Podlaskie,0.9814814814814814,0.40979955456570155,0.5478757620640435,0.1219806763285024,0.11643302180685358,0.3318009757738896,-0.04068051816958277

Wyliczenie wskaźnika syntetycznego będącego średnią arytmetyczną unormowanych wskaźników cząstkowych

In [7]:
mean_=np.zeros(16)
sum_=np.sum(prepared_data,axis=1).tolist()
for i in range(16):
  mean_[i]=sum_[i]/7
rows = ['Śląskie', 'Dolnośląskie', 'Mazowieckie', 'Małopolskie','Wielkopolskie', 'Zachodniopomorskie', 'Łódzkie', 'Pomorskie',
      'Opolskie', 'Kujawsko-pomorskie','Lubuskue', 'Podkarpackie', 'Świętokrzyskie', 'Lubelskie', 'Warmińsko-mazurskie', 'Podlaskie']
mean_indicator=np.column_stack((rows,mean_))
mean_indicators = pd.DataFrame(mean_indicator,columns=['Województwo','Wskaźnik syntetyczny'])
mean_indicators

            Województwo Wskaźnik syntetyczny
0               Śląskie  0.49950670303109435
1          Dolnośląskie   0.4174223022417856
2           Mazowieckie   0.6278464063633776
3           Małopolskie    0.583831892382742
4         Wielkopolskie    0.439167158260028
5    Zachodniopomorskie  0.33960451332279806
6               Łódzkie   0.4606039922010092
7             Pomorskie  0.42478679890466464
8              Opolskie   0.3109487124170126
9    Kujawsko-pomorskie  0.33963569994124293
10             Lubuskue   0.3091242783629847
11         Podkarpackie  0.45067705922629103
12       Świętokrzyskie   0.2863618030932774
13            Lubelskie   0.3941755853808727
14  Warmińsko-mazurskie   0.2806612283466667
15            Podlaskie  0.35267013626441274

Przeprowadzenie rankingu na podstawie wskaźnika syntetycznego oraz posortowanie województw względem rankingu

In [8]:
mean_indicators['Rank']=mean_indicators['Wskaźnik syntetyczny'].rank(ascending=False)
sorted=mean_indicators.sort_values(by=['Rank'])
sorted

            Województwo Wskaźnik syntetyczny  Rank
2           Mazowieckie   0.6278464063633776   1.0
3           Małopolskie    0.583831892382742   2.0
0               Śląskie  0.49950670303109435   3.0
6               Łódzkie   0.4606039922010092   4.0
11         Podkarpackie  0.45067705922629103   5.0
4         Wielkopolskie    0.439167158260028   6.0
7             Pomorskie  0.42478679890466464   7.0
1          Dolnośląskie   0.4174223022417856   8.0
13            Lubelskie   0.3941755853808727   9.0
15            Podlaskie  0.35267013626441274  10.0
9    Kujawsko-pomorskie  0.33963569994124293  11.0
5    Zachodniopomorskie  0.33960451332279806  12.0
8              Opolskie   0.3109487124170126  13.0
10             Lubuskue   0.3091242783629847  14.0
12       Świętokrzyskie   0.2863618030932774  15.0
14  Warmińsko-mazurskie   0.2806612283466667  16.0